spring.application.name=webdemo
spring.datasource.url=jdbc:postgresql://localhost:1995/test_db
spring.datasource.username=postgres
spring.datasource.password=1234567098123a
spring.jpa.hibernate.ddl-auto=update

spring.liquibase.enabled=false

